/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StartRouteImport } from './routes/start'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedRsvpRouteImport } from './routes/_authenticated/rsvp'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as AuthenticatedGuestsIdRouteImport } from './routes/_authenticated/guests_.$id'
import { Route as AuthenticatedGuestsExportRouteImport } from './routes/_authenticated/guests_.export'
import { Route as AuthenticatedGuestsImportRouteImport } from './routes/_authenticated/guests_.import'
import { Route as AuthenticatedInvitationChangesRouteImport } from './routes/_authenticated/invitation.changes'
import { Route as AuthenticatedInvitationCheckRouteImport } from './routes/_authenticated/invitation.check'
import { Route as AuthenticatedInvitationContentRouteImport } from './routes/_authenticated/invitation.content'
import { Route as AuthenticatedInvitationHistoryRouteImport } from './routes/_authenticated/invitation.history'
import { Route as AuthenticatedInvitationPreviewRouteImport } from './routes/_authenticated/invitation.preview'
import { Route as AuthenticatedInvitationVariantsRouteImport } from './routes/_authenticated/invitation.variants'
import { Route as AuthenticatedPlanBudgetRouteImport } from './routes/_authenticated/plan.budget'
import { Route as AuthenticatedPlanTasksRouteImport } from './routes/_authenticated/plan.tasks'
import { Route as AuthenticatedSettingsDataRouteImport } from './routes/_authenticated/settings.data'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedWeddingEventsRouteImport } from './routes/_authenticated/wedding.events'
import { Route as AuthenticatedWeddingNewRouteImport } from './routes/_authenticated/wedding.new'
import { Route as ITokenExpiredRouteImport } from './routes/i.$token_.expired'
import { Route as ITokenRsvpRouteImport } from './routes/i.$token_.rsvp'
import { Route as AuthenticatedCheckoutStatusIdRouteImport } from './routes/_authenticated/checkout_.status.$id'
import { Route as AuthenticatedGuestsImportBatchRouteImport } from './routes/_authenticated/guests_.import_.$batch'
import { Route as AuthenticatedPlanBudgetIdRouteImport } from './routes/_authenticated/plan.budget_.$id'
import { Route as AuthenticatedPlanTasksSuggestionsRouteImport } from './routes/_authenticated/plan.tasks_.suggestions'
import { Route as AuthenticatedWeddingEventsIdRouteImport } from './routes/_authenticated/wedding.events_.$id'
import { Route as ITokenRsvpReceiptRouteImport } from './routes/i.$token_.rsvp_.receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/_authenticated/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/_authenticated/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/_authenticated/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/_authenticated/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/_authenticated/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRsvpRoute = AuthenticatedRsvpRouteImport.update({
  id: '/_authenticated/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGuestsIdRoute = AuthenticatedGuestsIdRouteImport.update({
  id: '/_authenticated/guests_/$id',
  path: '/guests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGuestsExportRoute =
  AuthenticatedGuestsExportRouteImport.update({
    id: '/_authenticated/guests_/export',
    path: '/guests/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGuestsImportRoute =
  AuthenticatedGuestsImportRouteImport.update({
    id: '/_authenticated/guests_/import',
    path: '/guests/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationChangesRoute =
  AuthenticatedInvitationChangesRouteImport.update({
    id: '/_authenticated/invitation/changes',
    path: '/invitation/changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationCheckRoute =
  AuthenticatedInvitationCheckRouteImport.update({
    id: '/_authenticated/invitation/check',
    path: '/invitation/check',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationContentRoute =
  AuthenticatedInvitationContentRouteImport.update({
    id: '/_authenticated/invitation/content',
    path: '/invitation/content',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationHistoryRoute =
  AuthenticatedInvitationHistoryRouteImport.update({
    id: '/_authenticated/invitation/history',
    path: '/invitation/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationPreviewRoute =
  AuthenticatedInvitationPreviewRouteImport.update({
    id: '/_authenticated/invitation/preview',
    path: '/invitation/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvitationVariantsRoute =
  AuthenticatedInvitationVariantsRouteImport.update({
    id: '/_authenticated/invitation/variants',
    path: '/invitation/variants',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlanBudgetRoute = AuthenticatedPlanBudgetRouteImport.update({
  id: '/_authenticated/plan/budget',
  path: '/plan/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanTasksRoute = AuthenticatedPlanTasksRouteImport.update({
  id: '/_authenticated/plan/tasks',
  path: '/plan/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsDataRoute =
  AuthenticatedSettingsDataRouteImport.update({
    id: '/_authenticated/settings/data',
    path: '/settings/data',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/_authenticated/settings/team',
    path: '/settings/team',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWeddingEventsRoute =
  AuthenticatedWeddingEventsRouteImport.update({
    id: '/_authenticated/wedding/events',
    path: '/wedding/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWeddingNewRoute = AuthenticatedWeddingNewRouteImport.update({
  id: '/_authenticated/wedding/new',
  path: '/wedding/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenExpiredRoute = ITokenExpiredRouteImport.update({
  id: '/i/$token_/expired',
  path: '/i/$token/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRsvpRoute = ITokenRsvpRouteImport.update({
  id: '/i/$token_/rsvp',
  path: '/i/$token/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutStatusIdRoute =
  AuthenticatedCheckoutStatusIdRouteImport.update({
    id: '/_authenticated/checkout_/status/$id',
    path: '/checkout/status/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGuestsImportBatchRoute =
  AuthenticatedGuestsImportBatchRouteImport.update({
    id: '/_authenticated/guests_/import_/$batch',
    path: '/guests/import/$batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlanBudgetIdRoute =
  AuthenticatedPlanBudgetIdRouteImport.update({
    id: '/_authenticated/plan/budget_/$id',
    path: '/plan/budget/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlanTasksSuggestionsRoute =
  AuthenticatedPlanTasksSuggestionsRouteImport.update({
    id: '/_authenticated/plan/tasks_/suggestions',
    path: '/plan/tasks/suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWeddingEventsIdRoute =
  AuthenticatedWeddingEventsIdRouteImport.update({
    id: '/_authenticated/wedding/events_/$id',
    path: '/wedding/events/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ITokenRsvpReceiptRoute = ITokenRsvpReceiptRouteImport.update({
  id: '/i/$token_/rsvp_/receipt',
  path: '/i/$token/rsvp/receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/start': typeof StartRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/rsvp': typeof AuthenticatedRsvpRoute
  '/i/$token': typeof ITokenRoute
  '/guests/$id': typeof AuthenticatedGuestsIdRoute
  '/guests/export': typeof AuthenticatedGuestsExportRoute
  '/guests/import': typeof AuthenticatedGuestsImportRoute
  '/invitation/changes': typeof AuthenticatedInvitationChangesRoute
  '/invitation/check': typeof AuthenticatedInvitationCheckRoute
  '/invitation/content': typeof AuthenticatedInvitationContentRoute
  '/invitation/history': typeof AuthenticatedInvitationHistoryRoute
  '/invitation/preview': typeof AuthenticatedInvitationPreviewRoute
  '/invitation/variants': typeof AuthenticatedInvitationVariantsRoute
  '/plan/budget': typeof AuthenticatedPlanBudgetRoute
  '/plan/tasks': typeof AuthenticatedPlanTasksRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/wedding/events': typeof AuthenticatedWeddingEventsRoute
  '/wedding/new': typeof AuthenticatedWeddingNewRoute
  '/i/$token/expired': typeof ITokenExpiredRoute
  '/i/$token/rsvp': typeof ITokenRsvpRoute
  '/checkout/status/$id': typeof AuthenticatedCheckoutStatusIdRoute
  '/guests/import/$batch': typeof AuthenticatedGuestsImportBatchRoute
  '/plan/budget/$id': typeof AuthenticatedPlanBudgetIdRoute
  '/plan/tasks/suggestions': typeof AuthenticatedPlanTasksSuggestionsRoute
  '/wedding/events/$id': typeof AuthenticatedWeddingEventsIdRoute
  '/i/$token/rsvp/receipt': typeof ITokenRsvpReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/start': typeof StartRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/rsvp': typeof AuthenticatedRsvpRoute
  '/i/$token': typeof ITokenRoute
  '/guests/$id': typeof AuthenticatedGuestsIdRoute
  '/guests/export': typeof AuthenticatedGuestsExportRoute
  '/guests/import': typeof AuthenticatedGuestsImportRoute
  '/invitation/changes': typeof AuthenticatedInvitationChangesRoute
  '/invitation/check': typeof AuthenticatedInvitationCheckRoute
  '/invitation/content': typeof AuthenticatedInvitationContentRoute
  '/invitation/history': typeof AuthenticatedInvitationHistoryRoute
  '/invitation/preview': typeof AuthenticatedInvitationPreviewRoute
  '/invitation/variants': typeof AuthenticatedInvitationVariantsRoute
  '/plan/budget': typeof AuthenticatedPlanBudgetRoute
  '/plan/tasks': typeof AuthenticatedPlanTasksRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/wedding/events': typeof AuthenticatedWeddingEventsRoute
  '/wedding/new': typeof AuthenticatedWeddingNewRoute
  '/i/$token/expired': typeof ITokenExpiredRoute
  '/i/$token/rsvp': typeof ITokenRsvpRoute
  '/checkout/status/$id': typeof AuthenticatedCheckoutStatusIdRoute
  '/guests/import/$batch': typeof AuthenticatedGuestsImportBatchRoute
  '/plan/budget/$id': typeof AuthenticatedPlanBudgetIdRoute
  '/plan/tasks/suggestions': typeof AuthenticatedPlanTasksSuggestionsRoute
  '/wedding/events/$id': typeof AuthenticatedWeddingEventsIdRoute
  '/i/$token/rsvp/receipt': typeof ITokenRsvpReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/start': typeof StartRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/rsvp': typeof AuthenticatedRsvpRoute
  '/i/$token': typeof ITokenRoute
  '/_authenticated/guests_/$id': typeof AuthenticatedGuestsIdRoute
  '/_authenticated/guests_/export': typeof AuthenticatedGuestsExportRoute
  '/_authenticated/guests_/import': typeof AuthenticatedGuestsImportRoute
  '/_authenticated/invitation/changes': typeof AuthenticatedInvitationChangesRoute
  '/_authenticated/invitation/check': typeof AuthenticatedInvitationCheckRoute
  '/_authenticated/invitation/content': typeof AuthenticatedInvitationContentRoute
  '/_authenticated/invitation/history': typeof AuthenticatedInvitationHistoryRoute
  '/_authenticated/invitation/preview': typeof AuthenticatedInvitationPreviewRoute
  '/_authenticated/invitation/variants': typeof AuthenticatedInvitationVariantsRoute
  '/_authenticated/plan/budget': typeof AuthenticatedPlanBudgetRoute
  '/_authenticated/plan/tasks': typeof AuthenticatedPlanTasksRoute
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/wedding/events': typeof AuthenticatedWeddingEventsRoute
  '/_authenticated/wedding/new': typeof AuthenticatedWeddingNewRoute
  '/i/$token_/expired': typeof ITokenExpiredRoute
  '/i/$token_/rsvp': typeof ITokenRsvpRoute
  '/_authenticated/checkout_/status/$id': typeof AuthenticatedCheckoutStatusIdRoute
  '/_authenticated/guests_/import_/$batch': typeof AuthenticatedGuestsImportBatchRoute
  '/_authenticated/plan/budget_/$id': typeof AuthenticatedPlanBudgetIdRoute
  '/_authenticated/plan/tasks_/suggestions': typeof AuthenticatedPlanTasksSuggestionsRoute
  '/_authenticated/wedding/events_/$id': typeof AuthenticatedWeddingEventsIdRoute
  '/i/$token_/rsvp_/receipt': typeof ITokenRsvpReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/start'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/guests'
    | '/home'
    | '/plans'
    | '/publish'
    | '/rsvp'
    | '/i/$token'
    | '/guests/$id'
    | '/guests/export'
    | '/guests/import'
    | '/invitation/changes'
    | '/invitation/check'
    | '/invitation/content'
    | '/invitation/history'
    | '/invitation/preview'
    | '/invitation/variants'
    | '/plan/budget'
    | '/plan/tasks'
    | '/settings/data'
    | '/settings/team'
    | '/wedding/events'
    | '/wedding/new'
    | '/i/$token/expired'
    | '/i/$token/rsvp'
    | '/checkout/status/$id'
    | '/guests/import/$batch'
    | '/plan/budget/$id'
    | '/plan/tasks/suggestions'
    | '/wedding/events/$id'
    | '/i/$token/rsvp/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/start'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/guests'
    | '/home'
    | '/plans'
    | '/publish'
    | '/rsvp'
    | '/i/$token'
    | '/guests/$id'
    | '/guests/export'
    | '/guests/import'
    | '/invitation/changes'
    | '/invitation/check'
    | '/invitation/content'
    | '/invitation/history'
    | '/invitation/preview'
    | '/invitation/variants'
    | '/plan/budget'
    | '/plan/tasks'
    | '/settings/data'
    | '/settings/team'
    | '/wedding/events'
    | '/wedding/new'
    | '/i/$token/expired'
    | '/i/$token/rsvp'
    | '/checkout/status/$id'
    | '/guests/import/$batch'
    | '/plan/budget/$id'
    | '/plan/tasks/suggestions'
    | '/wedding/events/$id'
    | '/i/$token/rsvp/receipt'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/start'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/_authenticated/guests'
    | '/_authenticated/home'
    | '/_authenticated/plans'
    | '/_authenticated/publish'
    | '/_authenticated/rsvp'
    | '/i/$token'
    | '/_authenticated/guests_/$id'
    | '/_authenticated/guests_/export'
    | '/_authenticated/guests_/import'
    | '/_authenticated/invitation/changes'
    | '/_authenticated/invitation/check'
    | '/_authenticated/invitation/content'
    | '/_authenticated/invitation/history'
    | '/_authenticated/invitation/preview'
    | '/_authenticated/invitation/variants'
    | '/_authenticated/plan/budget'
    | '/_authenticated/plan/tasks'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/team'
    | '/_authenticated/wedding/events'
    | '/_authenticated/wedding/new'
    | '/i/$token_/expired'
    | '/i/$token_/rsvp'
    | '/_authenticated/checkout_/status/$id'
    | '/_authenticated/guests_/import_/$batch'
    | '/_authenticated/plan/budget_/$id'
    | '/_authenticated/plan/tasks_/suggestions'
    | '/_authenticated/wedding/events_/$id'
    | '/i/$token_/rsvp_/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StartRoute: typeof StartRoute
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedRsvpRoute: typeof AuthenticatedRsvpRoute
  ITokenRoute: typeof ITokenRoute
  AuthenticatedGuestsIdRoute: typeof AuthenticatedGuestsIdRoute
  AuthenticatedGuestsExportRoute: typeof AuthenticatedGuestsExportRoute
  AuthenticatedGuestsImportRoute: typeof AuthenticatedGuestsImportRoute
  AuthenticatedInvitationChangesRoute: typeof AuthenticatedInvitationChangesRoute
  AuthenticatedInvitationCheckRoute: typeof AuthenticatedInvitationCheckRoute
  AuthenticatedInvitationContentRoute: typeof AuthenticatedInvitationContentRoute
  AuthenticatedInvitationHistoryRoute: typeof AuthenticatedInvitationHistoryRoute
  AuthenticatedInvitationPreviewRoute: typeof AuthenticatedInvitationPreviewRoute
  AuthenticatedInvitationVariantsRoute: typeof AuthenticatedInvitationVariantsRoute
  AuthenticatedPlanBudgetRoute: typeof AuthenticatedPlanBudgetRoute
  AuthenticatedPlanTasksRoute: typeof AuthenticatedPlanTasksRoute
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedWeddingEventsRoute: typeof AuthenticatedWeddingEventsRoute
  AuthenticatedWeddingNewRoute: typeof AuthenticatedWeddingNewRoute
  ITokenExpiredRoute: typeof ITokenExpiredRoute
  ITokenRsvpRoute: typeof ITokenRsvpRoute
  AuthenticatedCheckoutStatusIdRoute: typeof AuthenticatedCheckoutStatusIdRoute
  AuthenticatedGuestsImportBatchRoute: typeof AuthenticatedGuestsImportBatchRoute
  AuthenticatedPlanBudgetIdRoute: typeof AuthenticatedPlanBudgetIdRoute
  AuthenticatedPlanTasksSuggestionsRoute: typeof AuthenticatedPlanTasksSuggestionsRoute
  AuthenticatedWeddingEventsIdRoute: typeof AuthenticatedWeddingEventsIdRoute
  ITokenRsvpReceiptRoute: typeof ITokenRsvpReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rsvp': {
      id: '/_authenticated/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof AuthenticatedRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests_/$id': {
      id: '/_authenticated/guests_/$id'
      path: '/guests/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof AuthenticatedGuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests_/export': {
      id: '/_authenticated/guests_/export'
      path: '/guests/export'
      fullPath: '/guests/export'
      preLoaderRoute: typeof AuthenticatedGuestsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests_/import': {
      id: '/_authenticated/guests_/import'
      path: '/guests/import'
      fullPath: '/guests/import'
      preLoaderRoute: typeof AuthenticatedGuestsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/changes': {
      id: '/_authenticated/invitation/changes'
      path: '/invitation/changes'
      fullPath: '/invitation/changes'
      preLoaderRoute: typeof AuthenticatedInvitationChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/check': {
      id: '/_authenticated/invitation/check'
      path: '/invitation/check'
      fullPath: '/invitation/check'
      preLoaderRoute: typeof AuthenticatedInvitationCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/content': {
      id: '/_authenticated/invitation/content'
      path: '/invitation/content'
      fullPath: '/invitation/content'
      preLoaderRoute: typeof AuthenticatedInvitationContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/history': {
      id: '/_authenticated/invitation/history'
      path: '/invitation/history'
      fullPath: '/invitation/history'
      preLoaderRoute: typeof AuthenticatedInvitationHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/preview': {
      id: '/_authenticated/invitation/preview'
      path: '/invitation/preview'
      fullPath: '/invitation/preview'
      preLoaderRoute: typeof AuthenticatedInvitationPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invitation/variants': {
      id: '/_authenticated/invitation/variants'
      path: '/invitation/variants'
      fullPath: '/invitation/variants'
      preLoaderRoute: typeof AuthenticatedInvitationVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan/budget': {
      id: '/_authenticated/plan/budget'
      path: '/plan/budget'
      fullPath: '/plan/budget'
      preLoaderRoute: typeof AuthenticatedPlanBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan/tasks': {
      id: '/_authenticated/plan/tasks'
      path: '/plan/tasks'
      fullPath: '/plan/tasks'
      preLoaderRoute: typeof AuthenticatedPlanTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthenticatedSettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wedding/events': {
      id: '/_authenticated/wedding/events'
      path: '/wedding/events'
      fullPath: '/wedding/events'
      preLoaderRoute: typeof AuthenticatedWeddingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wedding/new': {
      id: '/_authenticated/wedding/new'
      path: '/wedding/new'
      fullPath: '/wedding/new'
      preLoaderRoute: typeof AuthenticatedWeddingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token_/expired': {
      id: '/i/$token_/expired'
      path: '/i/$token/expired'
      fullPath: '/i/$token/expired'
      preLoaderRoute: typeof ITokenExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token_/rsvp': {
      id: '/i/$token_/rsvp'
      path: '/i/$token/rsvp'
      fullPath: '/i/$token/rsvp'
      preLoaderRoute: typeof ITokenRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout_/status/$id': {
      id: '/_authenticated/checkout_/status/$id'
      path: '/checkout/status/$id'
      fullPath: '/checkout/status/$id'
      preLoaderRoute: typeof AuthenticatedCheckoutStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/guests_/import_/$batch': {
      id: '/_authenticated/guests_/import_/$batch'
      path: '/guests/import/$batch'
      fullPath: '/guests/import/$batch'
      preLoaderRoute: typeof AuthenticatedGuestsImportBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan/budget_/$id': {
      id: '/_authenticated/plan/budget_/$id'
      path: '/plan/budget/$id'
      fullPath: '/plan/budget/$id'
      preLoaderRoute: typeof AuthenticatedPlanBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan/tasks_/suggestions': {
      id: '/_authenticated/plan/tasks_/suggestions'
      path: '/plan/tasks/suggestions'
      fullPath: '/plan/tasks/suggestions'
      preLoaderRoute: typeof AuthenticatedPlanTasksSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wedding/events_/$id': {
      id: '/_authenticated/wedding/events_/$id'
      path: '/wedding/events/$id'
      fullPath: '/wedding/events/$id'
      preLoaderRoute: typeof AuthenticatedWeddingEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token_/rsvp_/receipt': {
      id: '/i/$token_/rsvp_/receipt'
      path: '/i/$token/rsvp/receipt'
      fullPath: '/i/$token/rsvp/receipt'
      preLoaderRoute: typeof ITokenRsvpReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StartRoute: StartRoute,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedRsvpRoute: AuthenticatedRsvpRoute,
  ITokenRoute: ITokenRoute,
  AuthenticatedGuestsIdRoute: AuthenticatedGuestsIdRoute,
  AuthenticatedGuestsExportRoute: AuthenticatedGuestsExportRoute,
  AuthenticatedGuestsImportRoute: AuthenticatedGuestsImportRoute,
  AuthenticatedInvitationChangesRoute: AuthenticatedInvitationChangesRoute,
  AuthenticatedInvitationCheckRoute: AuthenticatedInvitationCheckRoute,
  AuthenticatedInvitationContentRoute: AuthenticatedInvitationContentRoute,
  AuthenticatedInvitationHistoryRoute: AuthenticatedInvitationHistoryRoute,
  AuthenticatedInvitationPreviewRoute: AuthenticatedInvitationPreviewRoute,
  AuthenticatedInvitationVariantsRoute: AuthenticatedInvitationVariantsRoute,
  AuthenticatedPlanBudgetRoute: AuthenticatedPlanBudgetRoute,
  AuthenticatedPlanTasksRoute: AuthenticatedPlanTasksRoute,
  AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedWeddingEventsRoute: AuthenticatedWeddingEventsRoute,
  AuthenticatedWeddingNewRoute: AuthenticatedWeddingNewRoute,
  ITokenExpiredRoute: ITokenExpiredRoute,
  ITokenRsvpRoute: ITokenRsvpRoute,
  AuthenticatedCheckoutStatusIdRoute: AuthenticatedCheckoutStatusIdRoute,
  AuthenticatedGuestsImportBatchRoute: AuthenticatedGuestsImportBatchRoute,
  AuthenticatedPlanBudgetIdRoute: AuthenticatedPlanBudgetIdRoute,
  AuthenticatedPlanTasksSuggestionsRoute:
    AuthenticatedPlanTasksSuggestionsRoute,
  AuthenticatedWeddingEventsIdRoute: AuthenticatedWeddingEventsIdRoute,
  ITokenRsvpReceiptRoute: ITokenRsvpReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
